name: deploy-container

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'container/**'
      - '.github/workflows/**'
  pull_request:
    branches: 
      - main
    paths: 
      - 'container/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependency
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Set up AWS-CLI version
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Sync dist folder with AWS
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
